superheroesproject/superheroes/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:superhero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create_new_superhero'),
    path('update/<int:superhero_id>/', views.update, name='update_superhero'),
    path('delete/<int:superhero_id>/', views.delete, name='delete')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

superheroesproject/superheroesproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superheroesproject/superheroes/models.py
from django.db import models

# Create your models here.


class Superhero(models.Model):
    superhero_name = models.CharField(max_length=200)
    alter_ego = models.CharField(max_length=50)
    primary_super_power = models.CharField(max_length=100)
    secondary_super_power = models.CharField(max_length=100)
    catchphrase = models.CharField(max_length=150)

    def __str__(self):
        return self.superhero_name

superheroesproject/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero
# Create your views here.


def index(request):
    all_superheroes = Superhero.objects.all()
    context = {
        'all_superheroes': all_superheroes
    }
    return render(request, 'superheroes/index.html', context)


def detail(request, superhero_id):
    single_superhero = Superhero.objects.get(pk=superhero_id)
    context = {
        'single_superhero': single_superhero
    }
    return render(request, 'superheroes/detail.html', context)


def create(request):
    if request.method == 'POST':
        superhero_name = request.POST.get('superhero_name')
        alter_ego = request.POST.get('alter_ego')
        primary_super_power = request.POST.get('primary_super_power')
        secondary_super_power = request.POST.get('secondary_super_power')
        catchphrase = request.POST.get('catchphrase')
        new_superhero = Superhero(superhero_name=superhero_name, alter_ego=alter_ego, primary_super_power=primary_super_power,
                                  secondary_super_power=secondary_super_power, catchphrase=catchphrase)
        new_superhero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')


def update(request, superhero_id):
    if request.method == 'POST':
        update_hero = Superhero.objects.get(pk=superhero_id)
        update_hero.superhero_name = request.POST.get('superhero_name')
        update_hero.alter_ego = request.POST.get('alter_ego')
        update_hero.primary_super_power = request.POST.get(
            'primary_super_power')
        update_hero.secondary_super_power = request.POST.get(
            'secondary_super_power')
        update_hero.catchphrase = request.POST.get('catchphrase')
        update_hero.save()
        return detail(request, superhero_id)
    else:
        update_hero = Superhero.objects.get(pk=superhero_id)
        context = {
            'update_hero': update_hero
        }
        return render(request, 'superheroes/update.html', context)


def delete(request, superhero_id):
    Superhero.objects.filter(pk=superhero_id).delete()
    return HttpResponseRedirect(reverse('superheroes:index'))

superheroesproject/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Superhero</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <h1 class="container-fluid"> Create a new hero! </h1>
    <form action="{% url 'superheroes:create_new_superhero' %}" method="post" class="container">
        {% csrf_token %}
        <div class="form-floating mb-3">
            <input type="text" name="superhero_name" id="superhero_name" class="form-control">
            <label for="superhero_name" class="form-label">Name:</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" name="alter_ego" id="alter_ego" class="form-control">
            <label for="alter_ego" class="form-label">Alter Ego:</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" name="primary_super_power" id="primary_super_power" class="form-control">
            <label for="primary_super_power" class="form-label">Primary Superpower:</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" name="secondary_super_power" id="secondary_super_power" class="form-control">
            <label for="secondary_super_power" class="form-label">Secondary Superpower:</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" name="catchphrase" id="catchphrase" class="form-control">
            <label for="catchphrase" class="form-label">Catchphrase:</label>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
        <a href="{% url 'superheroes:index' %}"  class="btn btn-primary">Back</a>
    </form>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

superheroesproject/superheroes/templates/superheroes/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Superhero</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <h1 class="containter"> Are you sure you want to delete {{update_hero.name}}? </h1>
    <form action="{% url 'superheroes:detail' selected_hero.id %}" method="get">
        {% csrf_token %}
        <input type="submit" value="Cancel" class="btn btn-primary">
    </form>
    <form action="{% url 'superheroes:delete' update_hero.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

superheroesproject/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Detail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <h1 class="container-fluid"> {{single_superhero.name}} </h1>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong> Alter Ego: </strong>  {{single_superhero.alter_ego}} </li>
        <li class="list-group-item"><strong> Primary Super Power: </strong>  {{single_superhero.primary_super_power}} </li>
        <li class="list-group-item"><strong> Secondary Super Power: </strong>  {{single_superhero.secondary_super_power}} </li>
        <li class="list-group-item"><strong> Catchphrase: </strong>  {{single_superhero.catchphrase}} </li>
    </ul>

    <div class="container-fluid">
        <a href="{% url 'superheroes:update_superhero' single_superhero.pk %}" class="btn btn-primary">Edit Superhero</a>
        <a href="{% url 'superheroes:delete' single_superhero.pk %}" class="btn btn-primary">Delete Superhero</a>
        <a href="{% url 'superheroes:index' %}" class="btn btn-primary">Select New Hero</a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

superheroesproject/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>List of Superheroes</h1>
    <ul>
        {% for superhero in all_superheroes %}
        <li><h2> {{superhero.superhero_name}} </h2>
        <a href="{% url 'superheroes:detail' superhero.id %}">See more info</a></li>
        {% endfor %}
    </ul>

    <button><a href="{% url 'superheroes:create_new_superhero' %}">Create New Superhero</a></button><br>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

superheroesproject/superheroes/templates/superheroes/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Editor</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <h1 class="container-fluid"> Updating {{update_superhero.name}} </h1>
    <form action="{% url 'superheroes:update_superhero' update_hero.id %}" method="post" class="container">
        {% csrf_token %}
        <div class="form-floating mb-3">
            <input type="text" name="name" id="name" class="form-control" value= "{{update_hero.name}}" >
            <label for="name" class="form-label">Name:</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" name="alter_ego_name" id="alter_ego_name" class="form-control" value= "{{update_superhero.alter_ego_name}}" >
            <label for="alter_ego_name" class="form-label">Alter Ego:</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" name="primary_super_ability" id="primary_super_ability" class="form-control" value= "{{update_superhero.primary_super_ability}}" >
            <label for="primary_super_ability" class="form-label">Primary Superpower:</label>
        </div>
         <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'superheroes:index' %}"  class="btn btn-primary">Back</a>
    </form>